version: '3.9'

services:

  postgres-test-container:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=api/cards

    ports:
      - 5000:5432